import { NextResponse } from 'next/server';
import type { ScanResponse } from '@/lib/types';

const mockScanResponse: ScanResponse = {
  totalAnomalies: 8,
  highRisk: 2,
  mediumRisk: 4,
  lowRisk: 2,
  scannedAt: '2025-01-14T16:30:00Z',
  results: [
    {
      assetSymbol: 'SOL',
      assetName: 'Solana',
      assetType: 'crypto',
      price: 178.92,
      anomalyType: 'rsi_overbought',
      anomalyLabel: 'RSI Quá mua',
      anomalyDescription: 'RSI đạt 78.4, vượt xa ngưỡng 70. Rủi ro điều chỉnh giảm ngắn hạn rất cao.',
      severity: 'high',
      detectedAt: '2025-01-14T16:30:00Z',
      currentValue: 78.4,
      normalRange: '30 - 70',
    },
    {
      assetSymbol: 'FPT',
      assetName: 'FPT Corp',
      assetType: 'stock',
      price: 142_500,
      anomalyType: 'rsi_overbought',
      anomalyLabel: 'RSI Quá mua',
      anomalyDescription: 'RSI đạt 73.8, vượt ngưỡng 70. Cổ phiếu có thể điều chỉnh trong vài phiên tới.',
      severity: 'high',
      detectedAt: '2025-01-14T16:30:00Z',
      currentValue: 73.8,
      normalRange: '30 - 70',
    },
    {
      assetSymbol: 'XRP',
      assetName: 'XRP',
      assetType: 'crypto',
      price: 2.48,
      anomalyType: 'rsi_oversold',
      anomalyLabel: 'RSI Quá bán',
      anomalyDescription: 'RSI rơi xuống 29.1, dưới ngưỡng 30. Có thể xuất hiện nhịp phục hồi kỹ thuật.',
      severity: 'medium',
      detectedAt: '2025-01-14T16:30:00Z',
      currentValue: 29.1,
      normalRange: '30 - 70',
    },
    {
      assetSymbol: 'BTC',
      assetName: 'Bitcoin',
      assetType: 'crypto',
      price: 104_850.5,
      anomalyType: 'volume_breakout',
      anomalyLabel: 'Khối lượng bùng nổ',
      anomalyDescription: 'Khối lượng giao dịch BTC tăng 42.5 tỷ USD, gấp 1.2 lần trung bình 20 ngày. Dòng tiền vào mạnh.',
      severity: 'medium',
      detectedAt: '2025-01-14T16:30:00Z',
      currentValue: 42_500_000_000,
      normalRange: '25B - 35B USD',
    },
    {
      assetSymbol: 'VIC',
      assetName: 'Vingroup',
      assetType: 'stock',
      price: 48_200,
      anomalyType: 'trend_reversal',
      anomalyLabel: 'Đảo chiều xu hướng',
      anomalyDescription: 'Giá VIC cắt xuống MA20 và hình thành mẫu hình nến giảm liên tiếp. Xu hướng ngắn hạn có thể đã đảo chiều.',
      severity: 'medium',
      detectedAt: '2025-01-14T16:30:00Z',
      currentValue: 48_200,
      normalRange: 'Trên MA20 (49,300)',
    },
    {
      assetSymbol: 'HPG',
      assetName: 'Hòa Phát Group',
      assetType: 'stock',
      price: 31_500,
      anomalyType: 'volatility_spike',
      anomalyLabel: 'Biến động tăng vọt',
      anomalyDescription: 'ATR HPG dãn rộng 2.1 lần so với trung bình 20 ngày. Biến động mạnh trong phiên tiếp theo.',
      severity: 'medium',
      detectedAt: '2025-01-14T16:30:00Z',
      currentValue: 2_450,
      normalRange: '800 - 1,200',
    },
    {
      assetSymbol: 'SJC',
      assetName: 'Vàng SJC',
      assetType: 'gold',
      price: 94_500_000,
      anomalyType: 'price_breakout',
      anomalyLabel: 'Phá vỡ kháng cự',
      anomalyDescription: 'Giá vàng SJC tiệm cận vùng kháng cự 95 triệu. Nếu phá vỡ, có thể tăng nhanh thêm.',
      severity: 'low',
      detectedAt: '2025-01-14T16:30:00Z',
      currentValue: 94_500_000,
      normalRange: '90M - 93M',
    },
    {
      assetSymbol: 'BNB',
      assetName: 'BNB',
      assetType: 'crypto',
      price: 712.8,
      anomalyType: 'macd_bullish',
      anomalyLabel: 'MACD Tích cực',
      anomalyDescription: 'MACD BNB vừa cắt lên đường tín hiệu, tạo tín hiệu mua. Khối lượng đi kèm tăng.',
      severity: 'low',
      detectedAt: '2025-01-14T16:30:00Z',
      currentValue: 12.5,
      normalRange: 'MACD > Signal',
    },
  ],
};

export async function GET() {
  return NextResponse.json({ data: mockScanResponse });
}
