import { NextResponse } from 'next/server';
import type { Expert } from '@/lib/types';

const mockExperts: Expert[] = [
  {
    id: 'expert-1',
    name: 'Nguyễn Văn An',
    avatar: '/avatars/expert-1.jpg',
    specialty: 'Chứng khoán phái sinh',
    rating: 4.8,
    reviewCount: 342,
    onlineStatus: 'online',
    bio: 'Chuyên gia phân tích kỹ thuật với 12 năm kinh nghiệm. Từng làm việc tại SSI và VCSC. Chuyên sâu về phân tích phái sinh và quản trị rủi ro.',
    recentAnalysisCount: 28,
    accuracyPercent: 78.5,
  },
  {
    id: 'expert-2',
    name: 'Trần Thị Bình',
    avatar: '/avatars/expert-2.jpg',
    specialty: 'Crypto & DeFi',
    rating: 4.6,
    reviewCount: 218,
    onlineStatus: 'online',
    bio: 'Blockchain researcher và crypto analyst. Đội ngũ founder tại một dự án DeFi lớn. Chuyên phân tích fundamental và on-chain data.',
    recentAnalysisCount: 45,
    accuracyPercent: 72.3,
  },
  {
    id: 'expert-3',
    name: 'Lê Minh Châu',
    avatar: '/avatars/expert-3.jpg',
    specialty: 'Vàng & Hàng hóa',
    rating: 4.9,
    reviewCount: 156,
    onlineStatus: 'away',
    bio: 'Chuyên gia thị trường vàng với 15 năm kinh nghiệm. Cố vấn cho nhiều công ty vàng lớn tại Việt Nam. Phân tích dựa trên yếu tố vĩ mô và cung cầu toàn cầu.',
    recentAnalysisCount: 12,
    accuracyPercent: 82.1,
  },
  {
    id: 'expert-4',
    name: 'Phạm Đức Dũng',
    avatar: '/avatars/expert-4.jpg',
    specialty: 'Chứng khoán cơ bản',
    rating: 4.5,
    reviewCount: 489,
    onlineStatus: 'online',
    bio: 'Chuyên gia phân tích cơ bản tại công ty chứng khoán BaoViet. Chuyên theo dõi các cổ phiếu bluechip và nhóm ngân hàng.',
    recentAnalysisCount: 35,
    accuracyPercent: 75.8,
  },
  {
    id: 'expert-5',
    name: 'Hoàng Thị Ember',
    avatar: '/avatars/expert-5.jpg',
    specialty: 'Macro Economics',
    rating: 4.7,
    reviewCount: 278,
    onlineStatus: 'offline',
    bio: 'Tiến sĩ kinh tế vĩ mô. Chuyên phân tích tác động của chính sách tiền tệ và tỷ giá đến thị trường tài chính Việt Nam.',
    recentAnalysisCount: 18,
    accuracyPercent: 80.2,
  },
  {
    id: 'expert-6',
    name: 'Võ Hoàng Giang',
    avatar: '/avatars/expert-6.jpg',
    specialty: 'Crypto Trading',
    rating: 4.3,
    reviewCount: 534,
    onlineStatus: 'online',
    bio: 'Full-time crypto trader với 6 năm kinh nghiệm. Chuyên giao dịch spot và futures trên Binance. Chia sẻ chiến lược trading hàng ngày.',
    recentAnalysisCount: 62,
    accuracyPercent: 68.7,
  },
  {
    id: 'expert-7',
    name: 'Đặng Minh Hiếu',
    avatar: '/avatars/expert-7.jpg',
    specialty: 'Chứng khoán kỹ thuật',
    rating: 4.4,
    reviewCount: 167,
    onlineStatus: 'away',
    bio: 'Kỹ sư phần mềm chuyển sang phân tích kỹ thuật. Chuyên sử dụng AI và machine learning trong phân tích biểu đồ chứng khoán.',
    recentAnalysisCount: 22,
    accuracyPercent: 73.4,
  },
  {
    id: 'expert-8',
    name: 'Bùi Thu Hương',
    avatar: '/avatars/expert-8.jpg',
    specialty: 'NFT & Web3',
    rating: 4.2,
    reviewCount: 95,
    onlineStatus: 'offline',
    bio: 'NFT collector và Web3 enthusiast. Đánh giá các dự án NFT và GameFi mới. Phân tích xu hướng metaverse và digital ownership.',
    recentAnalysisCount: 15,
    accuracyPercent: 65.8,
  },
];

export async function GET() {
  return NextResponse.json({
    data: mockExperts,
    total: mockExperts.length,
  });
}
