import { NextResponse } from 'next/server';
import type { AlertTemplate } from '@/lib/types';

const mockTemplates: AlertTemplate[] = [
  {
    id: 'tpl-1',
    name: 'RSI vượt 70 (Quá mua)',
    description: 'Cảnh báo khi chỉ số RSI vượt mức 70, cho thấy tài sản đang ở vùng quá mua và có thể điều chỉnh giảm trong ngắn hạn.',
    condition: 'RSI > 70',
    indicatorType: 'RSI',
    assetType: 'all',
    riskLevel: 'high',
  },
  {
    id: 'tpl-2',
    name: 'RSI giảm dưới 30 (Quá bán)',
    description: 'Cảnh báo khi RSI rơi dưới 30, cho thấy tài sản đang ở vùng quá bán và có thể bật tăng.',
    condition: 'RSI < 30',
    indicatorType: 'RSI',
    assetType: 'all',
    riskLevel: 'medium',
  },
  {
    id: 'tpl-3',
    name: 'Giá cắt mất MA20',
    description: 'Cảnh báo khi giá đóng cửa dưới đường trung bình động 20 ngày, tín hiệu xu hướng ngắn hạn suy yếu.',
    condition: 'Giá < MA20',
    indicatorType: 'MA',
    assetType: 'all',
    riskLevel: 'medium',
  },
  {
    id: 'tpl-4',
    name: 'Khối lượng tăng 200% so với 20 ngày',
    description: 'Cảnh báo khi khối lượng giao dịch tăng gấp 3 lần so với trung bình 20 ngày, cho thấy sự quan tâm bất thường từ thị trường.',
    condition: 'Volume > 3 * AvgVolume20',
    indicatorType: 'volume',
    assetType: 'all',
    riskLevel: 'high',
  },
  {
    id: 'tpl-5',
    name: 'ATR dãn rộng bùng nổ biến động',
    description: 'Cảnh báo khi ATR dãn rộng vượt 2 lần trung bình, dự báo biến động giá mạnh trong phiên tiếp theo.',
    condition: 'ATR > 2 * AvgATR',
    indicatorType: 'ATR',
    assetType: 'all',
    riskLevel: 'high',
  },
  {
    id: 'tpl-6',
    name: 'MACD cắt xuống tín hiệu',
    description: 'Tín hiệu bán khi đường MACD cắt xuống đường tín hiệu (signal line), xác nhận xu hướng giảm.',
    condition: 'MACD cắt xuống Signal',
    indicatorType: 'MACD',
    assetType: 'all',
    riskLevel: 'high',
  },
  {
    id: 'tpl-7',
    name: 'Giá phá vỡ hỗ trợ 50 ngày',
    description: 'Cảnh báo khi giá phá vỡ mức hỗ trợ quan trọng tại MA50, rủi ro giảm sâu trong trung hạn.',
    condition: 'Giá < MA50',
    indicatorType: 'MA',
    assetType: 'stock',
    riskLevel: 'high',
  },
  {
    id: 'tpl-8',
    name: 'MACD cắt lên tín hiệu',
    description: 'Tín hiệu mua khi đường MACD cắt lên đường tín hiệu, xác nhận xu hướng tăng mới.',
    condition: 'MACD cắt lên Signal',
    indicatorType: 'MACD',
    assetType: 'all',
    riskLevel: 'low',
  },
  {
    id: 'tpl-9',
    name: 'Giá đạt đỉnh 52 tuần',
    description: 'Cảnh báo khi giá chạm mức cao nhất trong 52 tuần, có thể tiếp tục tăng hoặc chốt lời.',
    condition: 'Giá >= High52W',
    indicatorType: 'price',
    assetType: 'all',
    riskLevel: 'medium',
  },
  {
    id: 'tpl-10',
    name: 'Giá chạm đáy 52 tuần',
    description: 'Cảnh báo khi giá rơi xuống mức thấp nhất trong 52 tuần, cơ hội mua giá rẻ hoặc cắt lỗ.',
    condition: 'Giá <= Low52W',
    indicatorType: 'price',
    assetType: 'all',
    riskLevel: 'medium',
  },
  {
    id: 'tpl-11',
    name: 'Vàng vượt ngưỡng kháng cự',
    description: 'Cảnh báo khi giá vàng vượt ngưỡng kháng cự tâm lý quan trọng.',
    condition: 'Giá vàng > ngưỡng kháng cự',
    indicatorType: 'price',
    assetType: 'gold',
    riskLevel: 'high',
  },
  {
    id: 'tpl-12',
    name: 'Bitcoin halving sắp tới',
    description: 'Nhắc nhở sự kiện halving Bitcoin sắp diễn ra trong 30 ngày.',
    condition: 'Halving trong 30 ngày',
    indicatorType: 'event',
    assetType: 'crypto',
    riskLevel: 'low',
  },
];

export async function GET() {
  return NextResponse.json({
    data: mockTemplates,
    total: mockTemplates.length,
  });
}
